WebAutoParkWeek3
Dev-incubator/WebAutoparkDima pull request #4
Opened 2021-05-31 10:51 UTC by dzmitri-litvinov

Add functionality for SpareParts and VehicleTypes

2021-06-01 19:13 UTC, UNDogMan requested changes
I leave some comments, ask me if any question.

2021-06-01 19:13 UTC, UNDogMan commented on WebAutopark/Views/VehicleType/Create.cshtml
> +</form>
You can use tag or html helpers for easy form creation.
Article about [tag helpers](https://metanit.com/sharp/aspnet5/10.1.php) and [tag helpers for forms](https://metanit.com/sharp/aspnet5/10.4.php).
Article about [html helpers and their creation](https://metanit.com/sharp/aspnet5/9.1.php) and [html helpers for forms](https://metanit.com/sharp/aspnet5/9.2.php)

2021-06-02 15:25 UTC, PushMeNow requested changes
I did some comments. Let me know if any questions

2021-06-02 15:25 UTC, PushMeNow commented on WebAutopark/Views/SparePart/Create.cshtml
> +</form>
Use html helpers for forms https://metanit.com/sharp/aspnet5/9.2.php

2021-06-02 15:25 UTC, PushMeNow commented on WebAutopark/Views/SparePart/Index.cshtml
> +                        <button class="btn btn-primary" type="submit">Delete</button>
Why here button? link tag is working without it.

2021-06-03 15:50 UTC, dzmitri-litvinov commented on WebAutopark/Views/SparePart/Index.cshtml
> +</table>*@
Done

2021-06-03 15:51 UTC, dzmitri-litvinov commented on WebAutopark/Views/VehicleType/Create.cshtml
> +</form>
![image](https://user-images.githubusercontent.com/79978383/120674346-acebaa00-c49c-11eb-84ed-dcc3663271a8.png)
Done

2021-06-03 15:52 UTC, dzmitri-litvinov commented on WebAutopark/Views/SparePart/Create.cshtml
> +</form>
![image](https://user-images.githubusercontent.com/79978383/120674445-c4c32e00-c49c-11eb-86ee-b663d18d32da.png)
Done

2021-06-03 15:52 UTC, dzmitri-litvinov commented on WebAutopark/Views/SparePart/Index.cshtml
> +                        <button class="btn btn-primary" type="submit">Delete</button>
![image](https://user-images.githubusercontent.com/79978383/120674543-ddcbdf00-c49c-11eb-8738-107e159f35d3.png)
Done in all the project

2021-06-03 18:39 UTC, PushMeNow approved these changes

2021-06-03 18:56 UTC, UNDogMan approved these changes
Approve

2021-06-03 19:18 UTC, merged