Web auto park week4
Dev-incubator/WebAutoparkDima pull request #5
Opened 2021-06-07 07:00 UTC by dzmitri-litvinov

2021-06-07 17:57 UTC, PushMeNow requested changes

2021-06-07 17:57 UTC, PushMeNow commented on WebAutopark/Controllers/VehicleController.cs
> +        public IActionResult GetById(int id)
Usually this page has name Details.

2021-06-07 17:57 UTC, PushMeNow commented on WebAutopark/Controllers/VehicleController.cs
> +            ViewBag.MaxKm = vehicle.GetMaxKm().ToString("0.00");
Why do u need additional variables in viewbag? U can use auto-props in this case

2021-06-07 17:57 UTC, PushMeNow commented on WebAutopark/Controllers/VehicleController.cs
> +
Wait what? U already have done it in vehicle repo.

2021-06-07 17:57 UTC, PushMeNow commented on WebAutopark/Controllers/VehicleController.cs
> +            var vehicleTypes = _vehicleTypeRepository.GetAll().ToList();
Hm... Why do you need cal ToList here?

2021-06-07 17:57 UTC, PushMeNow commented on WebAutopark/Controllers/VehicleController.cs
> +        }
Creat  new method in vehicle repo for ordering and make this action on sql side

2021-06-07 17:57 UTC, PushMeNow commented on WebAutopark/Extentions/VehicleExtentions.cs
> +    public static class VehicleExtentions
I don't see the reason in these extensions. Do it by auto-props.

2021-06-07 17:57 UTC, PushMeNow commented on WebAutopark/Views/Vehicle/Create.cshtml
> +    ViewData["Title"] = "Home Page";
Why all your pages have title "Home page"?

2021-06-08 10:16 UTC, dzmitri-litvinov commented on WebAutopark/Controllers/VehicleController.cs
> +        public IActionResult GetById(int id)
![image](https://user-images.githubusercontent.com/79978383/121168521-b9d11a80-c85b-11eb-903d-72b25dfe9f87.png)
Done

2021-06-08 10:28 UTC, dzmitri-litvinov commented on WebAutopark/Controllers/VehicleController.cs
> +            ViewBag.MaxKm = vehicle.GetMaxKm().ToString("0.00");
![image](https://user-images.githubusercontent.com/79978383/121170130-75467e80-c85d-11eb-9213-bf1c0e0bdd38.png)
Done

2021-06-08 11:04 UTC, dzmitri-litvinov commented on WebAutopark/Controllers/VehicleController.cs
> +
![image](https://user-images.githubusercontent.com/79978383/121174239-631b0f00-c862-11eb-9da6-82311ec700f5.png)
Done

2021-06-08 11:05 UTC, dzmitri-litvinov commented on WebAutopark/Views/Vehicle/Create.cshtml
> +    ViewData["Title"] = "Home Page";
Fixed

2021-06-08 11:05 UTC, dzmitri-litvinov commented on WebAutopark/Extentions/VehicleExtentions.cs
> +    public static class VehicleExtentions
![image](https://user-images.githubusercontent.com/79978383/121174461-9c537f00-c862-11eb-9a44-2b30ef329601.png)
Done

2021-06-08 11:21 UTC, dzmitri-litvinov commented on WebAutopark/Controllers/VehicleController.cs
> +            var vehicleTypes = _vehicleTypeRepository.GetAll().ToList();
![image](https://user-images.githubusercontent.com/79978383/121176317-be4e0100-c864-11eb-8de6-8df6dc9fa9bc.png)
Removed

2021-06-08 13:46 UTC, dzmitri-litvinov commented on WebAutopark/Controllers/VehicleController.cs
> +        }
![image](https://user-images.githubusercontent.com/79978383/121196375-1abb1b80-c879-11eb-923f-f2cf159fc642.png)
Done

2021-06-08 18:48 UTC, UNDogMan requested changes

2021-06-08 18:48 UTC, UNDogMan commented on WebAutopark.DAL/Repositories/VehicleRepository.cs
> +            }
U dont need switch case here. Use if.

2021-06-08 18:48 UTC, UNDogMan commented on WebAutopark/Controllers/OrderController.cs
> +            order.OrderElements = ordersElements.Where(o => o.OrderId == id).ToList();
Move this to database as u did it for order-vehicle.

2021-06-09 07:33 UTC, dzmitri-litvinov commented on WebAutopark.DAL/Repositories/VehicleRepository.cs
> +            }
![image](https://user-images.githubusercontent.com/79978383/121312472-15f47700-c90e-11eb-86e2-95e01c38371c.png)
Done

2021-06-09 07:35 UTC, dzmitri-litvinov commented on WebAutopark/Controllers/OrderController.cs
> +            order.OrderElements = ordersElements.Where(o => o.OrderId == id).ToList();
![image](https://user-images.githubusercontent.com/79978383/121312651-43412500-c90e-11eb-883d-78b25371f484.png)
It's done local and will be pushed in the next PR

2021-06-09 08:49 UTC, UNDogMan approved these changes

2021-06-11 19:10 UTC, PushMeNow requested changes

2021-06-11 19:10 UTC, PushMeNow commented on WebAutopark.DAL/Repositories/OrdersElementsRepository.cs
> +        private const string sqlQueryGetAllString = "SELECT OE.*, SP.Id SPID, SP.PartName FROM OrdersElements OE, SpareParts SP WHERE OE.SparePartId = SP.Id";
It is bad syntax. Use JOIN here.

2021-06-11 19:10 UTC, PushMeNow commented on WebAutopark.DAL/Repositories/OrdersRepository.cs
> +            "FROM Orders O, Vehicles V WHERE O.VehicleId = V.Id";
again use join

2021-06-11 19:10 UTC, PushMeNow commented on WebAutopark.DAL/Repositories/VehicleRepository.cs
> +        private string SqlOrdering(string orderingCol, string orderingDir)
Lets make 'orderingDir' like enum

2021-06-11 19:10 UTC, PushMeNow commented on WebAutopark.DAL/Repositories/VehicleRepository.cs
> +            }
Not need skip ASC ending. Make switch and add ASC or DESC. It will look more user friendly

2021-06-11 19:59 UTC, dzmitri-litvinov commented on WebAutopark.DAL/Repositories/VehicleRepository.cs
> +            }
![image](https://user-images.githubusercontent.com/79978383/121742592-b44c2c80-cb08-11eb-998f-3731609dd791.png)
done

2021-06-11 20:00 UTC, dzmitri-litvinov commented on WebAutopark.DAL/Repositories/VehicleRepository.cs
> +        private string SqlOrdering(string orderingCol, string orderingDir)
![image](https://user-images.githubusercontent.com/79978383/121742684-d6de4580-cb08-11eb-97e7-a46cfd97e34c.png)
Done

2021-06-11 21:25 UTC, dzmitri-litvinov commented on WebAutopark.DAL/Repositories/OrdersElementsRepository.cs
> +        private const string sqlQueryGetAllString = "SELECT OE.*, SP.Id SPID, SP.PartName FROM OrdersElements OE, SpareParts SP WHERE OE.SparePartId = SP.Id";
Will be fixed in the next PR

2021-06-11 21:25 UTC, dzmitri-litvinov commented on WebAutopark.DAL/Repositories/OrdersRepository.cs
> +            "FROM Orders O, Vehicles V WHERE O.VehicleId = V.Id";
Will be fixed in the next PR

2021-06-12 15:51 UTC, PushMeNow approved these changes

2021-06-12 15:51 UTC, merged